### ISSUE TITLE
Please put the data of these files (train-annotations-bbox.csv, train-images-boxable.csv)

### ISSUE THREAD

**Issue by chandrasagar007** [blackbird71SR/Object-Detection-in-RGBD-datasets#2]

**Comment by blackbird71SR** [comment]
!wget "https://storage.googleapis.com/openimages/2018_04/class-descriptions.csv"
!wget "https://datasets.figure-eight.com/figure_eight_datasets/open-images/train-annotations-bbox.csv"
!wget "https://datasets.figure-eight.com/figure_eight_datasets/open-images/train-images-boxable.csv"

Sorry for the late reply! All the files are downloaded in the notebook including images. Check Models.ipynb
